# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: format-rust
        name: Format Rust
        language: script
        entry: cargo fmt --all && cargo clippy --fix --allow-dirty --allow-staged
        files: \.x$
