site_name: Robot Insprill
site_description: Documentation for Robot Insprill

site_url: https://robot-insprill.rtfd.io/
repo_name: insprill/robot-insprill
repo_url: https://github.com/Insprill/robot-insprill/
edit_uri: blob/master/docs/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Hosting:
      - hosting/index.md
      - Docker: hosting/docker.md
      - Native: hosting/native.md
  - Configuration:
      - configuration/index.md
      - Environment Variables: configuration/env.md
      - Custom Properties:
        - Messages: configuration/props/messages.md
        - Emojis: configuration/props/emojis.md
      - Automatic Actions: configuration/autoactions.md
      - Statistic Channels: configuration/statchannels.md
      - Restricted Channels: configuration/channelrestrictions.md
      - Forms: configuration/forms.md
  - Discord:
      - Permissions: discord/perms.md
  - Contributing:
      - contributing/index.md
      - Development Environment: contributing/env.md
      - Implementation Guides: contributing/guides.md
      - Building Documentation: contributing/docs.md
