# Built in command configuration
builtins:
  clear: true
  binfiles:
    enabled: true
    upload: LUCKO_PASTE
    
codebin:
  services:
    HASTEBIN_LEGACY:
        - paste.md-5.net
        - paste.helpch.at
    SOURCE_BIN:
      - sourceb.in
    LUCKO_PASTE:
      - paste.insprill.net
    PASTEBIN:
      - pastebin.com
  